### PR TITLE
Add tag component

### PR DESCRIPTION
**Pull request by kaje94**
## Purpose
Add tag component based on https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/tag/README.md

## Related Issue
Resolves https://github.com/estruyf/vscode-community-ui-toolkit/issues/8

## Sample screenshots
Screenshot 2024-08-22 at 05 24 20
Screenshot 2024-08-22 at 05 23 16
Screenshot 2024-08-22 at 05 23 51
Screenshot 2024-08-22 at 05 23 38

### CODE REVIEW

**Comment by estruyf** [comment]
@kaje94 looks great! Good job. Just one small remark.

**Comment by kaje94** [comment]
@estruyf, Could you please clarify the remark?

**Comment by estruyf** [comment]
Check the code review. You used Calc, but there isn't anything to be calculated. So you can just specify the value.

**Comment by kaje94** [comment]
Thanks for pointing it out. I've updated the PR.

**Comment by estruyf** [comment]
Thanks @kaje94!

**Pull request merged**
