### PR TITLE
Add high contrast light theme to dev testing environment

### PR DESCRIPTION
**Pull request by hawkticehurst**
### Description of changes

- Adds `high-contrast-light.css`
- Renames `high-contrast.css` to `high-contrast-dark.css`
- Updates `dev/index.html` to accommodate above changes

Other tweaks:

- Removes GitLens and RemoteHub related tokens from `high-contrast-dark.css`
- Changes `--vscode-editor-font-family` value back to VS Code default
- Add `cursor: pointer` hover styles to nav buttons
- Change nav button text from "Light version" and "Dark version" to just "Light" and "Dark"

### CODE REVIEW

**Comment by hawkticehurst** [comment]
cc @estruyf for review (since I don't have permissions to request PR reviews on this repo)

**Comment by estruyf** [comment]
@hawkticehurst, I've added you as a collaborator to the project. You should have received an invite.

**Comment by hawkticehurst** [comment]
thanks, i got it!

**Review by estruyf — APPROVED** [review]
Looks great! Thanks @hawkticehurst 🙏

**Pull request merged**
